Require ps to build on arm64 Mac 4.1.0-dev
I tried to install pak on a fresh install of 4.1.0-dev on an arm64 mac and got the following problem, which resolved itself after ps was installed:

* installing *source* package ‘pkgcache’ ...
** package ‘pkgcache’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: .onLoad failed in loadNamespace() for 'processx', details:
  call: loadNamespace(x)
  error: there is no package called ‘ps’
Execution halted
ERROR: lazy loading failed for package ‘pkgcache’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/pkgcache’
Warning in install.packages :
  installation of package ‘pkgcache’ had non-zero exit status